### ISSUE TITLE
Bouncy Path Guy

### ISSUE THREAD

**Issue by slabrant** [BradleyHendrickson/gwj-73#4]
The enemy that follows a path currently inverts its velocity on detecting an object in the direction it's heading.  
We want a variety of the enemy that instead of inverting x and y, it only inverts the direction that is orthogonal to the collision surface.  
This will allow the enemy to bounce around a bit less predictably. More preferred, it will allow it to zig-zag along a passage. This is why the enemy at the top of level-1 is at a weird angle in a narrow passage.

**Comment by slaker333** [comment]
3a7753daba9077c5df9dc37cdd6384dce0cd3180
